### PR TITLE
Bug fix 349: handled issue of missing test directory at location of s…

### PR DESCRIPTION
**Pull request by mattmarquard**
…tatic_path

### CODE REVIEW

**Comment by nursix** [comment]
Good idea.

However, better would be to disable the menu item if the directory doesn't exist, or at least inform the user that we're not showing anything because there isn't anything to show. As you have it here, it would be just empty, and not obvious for the user why (<=which you can be sure will be reported as a bug).

At least, try something like

    response.warning = T("No test results available")

in the except-branch.

Note that the test suite that produces the test results is deprecated and not working at the moment ;) so this "bug" is only the very tip of the iceberg.

What is really needed is something that actually produces test results - and while we don't have that, I would recommend to comment this menu item and put in a ToDo (in s3menus.py). No point to show a menu item that doesn't ever work.

**Comment by nursix** [comment]
We do have a new smoke test functionality, however - it's just not wired up to show any test results inside the application. And while it isn't, there's no point to have that menu item visible for the users.

**Comment by mattmarquard** [comment]
Thanks for the review @nursix . That response warning is definitely a better way to communicate to the user there are no test results. I'll do what you said regarding removing the menu item and adding a ToDo.

**Comment by nursix** [comment]
Superseded by:
https://github.com/nursix/eden/commit/656045f74ef5ccfacf86cf722a58ea9683c4759b
...hence closing this one.

Thanks Matt :)

**Pull request closed without merging**
