### PR TITLE
SHARE template first cut

### PR DESCRIPTION
**Pull request by waidyanatha**
What was developed to based on initial understanding of the Sri Lanka UN-RCO shared requirements

### CODE REVIEW

**Comment by nursix** [comment]
Do you want to rebase this so that it can be reviewed more easily?

**Comment by waidyanatha** [comment]
OK I will try. I've never been able to rebase or squash with these instructions: http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/Git#Detaileddescriptionsofworkflowsteps

Work around is - I usually delete my branch, then fork again, make a new clone on my laptop, copy paste the files folders with new code changes, then push to my branch to submit a clean pull request. This usually takes time with cloning through the vpn in China.

**Comment by nursix** [comment]
Try this in your local repository:
```
git fetch upstream
git rebase upstream/master
git push -f origin master
```

And then in future, if you have made commits to your local master, pull from upstream like this:
```
git pull --rebase upstream master
```

But the better strategy is to not commit to master directly in the first place, but work in story branches:

1. Create a story branch, edit it, then commit to story branch:
```
git checkout -b story_branch
[...edit...]
git commit -a
```

2. Pull upstream to master:
```
git checkout master
git pull upstream master
```

3. Rebase the story branch before merging it:
```
git checkout story_branch
git rebase master
```

4. Merge+squash+commit story branch into master (after rebasing the story branch):
```
git checkout master
git merge --squash story_branch
git commit -a
```

5. Delete the story branch when done:
```
git branch -D story_branch
```

This is my workflow, at least. I never commit anything directly to master - the master branch is only a merge/publish-platform.

**Comment by waidyanatha** [comment]
Thanks a lot, I think it worked and have submitted a new PR: https://github.com/sahana/eden/pull/1455

**Pull request closed without merging**
