### PR TITLE
bugfix for send_tweet + location update for SAMBRO/NP + remove the copy button: not working

### PR DESCRIPTION
**Pull request by biplovbhandari**

### CODE REVIEW

**Comment by nursix** [comment]
create?from_record only works with default form - not implemented for custom forms (cap_info uses a custom form, that's why it doesn't work)

**Comment by biplovbhandari** [comment]
@flavour Please merge

**Comment by flavour** [comment]
If the copy button is wanted, but isn't working yet, I suggest commenting it rather than removing it completely?
Can add the reason why it's not working yet

**Comment by biplovbhandari** [comment]
@flavour Done!

**Comment by biplovbhandari** [comment]
@flavour this also contains the bugfix for the tweet. Can you review and if okay merge?

**Comment by flavour** [comment]
Yup, spotted that - although it didn't seem problematic so wouldn't have mattered if I hadn't as it happens ;)

Thanks :)

**Comment by biplovbhandari** [comment]
I am testing for the Nepal training for the 2nd week of December. Might post some (silly!) questions in the group and some PR. Thanks for the merge :)

**Pull request merged**
