### PR TITLE
improve zh-tw translation

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
anybody here?

**Comment by flavour** [comment]
Very hard for me to review this since every line has been changed...I guess this is due to line-endings.
The key things I look for are correct use of variables as this can crash if incorrect.
We have 2 optiosn for proceeding: (A) You resubmit without changing line-endings so I can see what you've changed or (B) I delegate responsibility for this translation to you.
Can I assume that you've done at least partial testing with this new file?
Do you have a live deployment of the software?

**Comment by PeterDaveHello** [comment]
I'll fix it soon and then ping you, thanks!

**Comment by PeterDaveHello** [comment]
@flavour sorry for the very late response, this got forgotten totally.

I checked the diff and looks like the line-endings weren't changed, all the changed lines should contain translation update, would you please take a look?

**Pull request merged**
