### PR TITLE
minor tweaks

### PR DESCRIPTION
**Pull request by biplovbhandari**

### CODE REVIEW

**Comment by flavour** [comment]
I am wary about changing the default Event Types, as this is a list which came from somewhere official.
If your local users don't like it then create a copy & use that one instead

**Comment by nursix** [comment]
Original source were Canadian EMS incident categories ;)

Funny enough, they use consistently singular terms - as do the rest of the default values here.

I tend to agree with Biplov to change the defaults here - makes more sense IMO.

**Comment by nursix** [comment]
Looking around: FEMA, UN - nobody uses plurals for event/incident type taxonomy. Looks rather strange that we do, and just for those two.

**Comment by flavour** [comment]
ok ;)

**Pull request merged**
